/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as IndexRouteImport } from './routes/index'

const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attractions' | '/destinations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attractions' | '/destinations'
  id: '__root__' | '/' | '/attractions' | '/destinations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttractionsRoute: typeof AttractionsRoute
  DestinationsRoute: typeof DestinationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttractionsRoute: AttractionsRoute,
  DestinationsRoute: DestinationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
